# Site settings
title: Juan Pablo López Alduncin
description: My resume
baseurl: "JuanPLopez.github.io" # the subpath of your site, e.g. /blog
url: "JuanPLopez" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Juan Pablo López Alduncin
user_description: I’m an Argentinean double degree candidate at ESCP Europe. I’ve proven to be dynamic and proactive, with excellent English language skills and adaptation to change acquired from having lived in diverse emerging markets including Africa, South America, the Middle East and Asia. I’m currently looking for a summer internship that will enable me to add value and gain acknowledgment based on performance and results. 

user_title: ESCP Europe MiM Candidate
email: jlopezalduncin@gmail.com
# twitter_username: lorem_ipsum
github_username:  JuanPlopez
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: "UA-146562851-1"
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-146562851-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-146562851-1');
</script>

exclude: ['package.json', 'src' , 'node_modules']
